### ISSUE TITLE
Update repo

### ISSUE THREAD

**Issue by alaaNfissi** [tdurieux/anonymous_github#183]
Hello,

I've been trying to update my repository by forcing it but it's not working. (I need this to work asap due to deadline)

Best regards.

**Comment by tdurieux** [comment]
I just fixed the bug, plus force update your repository.

**Comment by alaaNfissi** [comment]
Thank you, but It's not updated, I still have the old version.

**Comment by tdurieux** [comment]
is your repo is up to date now?

**Comment by alaaNfissi** [comment]
Yes, but not with the latest commit, some changes are not there yet.

**Comment by tdurieux** [comment]
what is the last commit in your repo and when was it push?

**Comment by alaaNfissi** [comment]
It was pushed 4 hours ago, fix: cd

**Comment by tdurieux** [comment]
what is the commit sha

**Comment by tdurieux** [comment]
It should be good now

**Comment by alaaNfissi** [comment]
Yes, thank you for your help. Should I keep working or it's better to wait sometime for the problem to be solved ?

**Comment by tdurieux** [comment]
Yes, the problem is solved.
