### ISSUE TITLE
Duplicated Code in Notebooks

### ISSUE THREAD

**Issue by mnagired** [tdurieux/anonymous_github#184]
Hi there,

When I go to any of the Jupyter Notebooks in my anonymized repository, the entire notebook is replicated. Specifically, after where the notebook should have ended, it is copy pasted in its entirety right under. So, the overall notebook contains everything twice. Please note that the original notebooks (in GitHub) do not have this problem.

I don't recall having this issue prior to the resolution of #181. Could you please take a look and let me know @tdurieux? 

Thank you so much for your time, I really appreciate it :)

**Comment by tdurieux** [comment]
I think it was present before that since I did not touch this code for a really long time.

fixed by #[8221b2e](https://github.com/tdurieux/anonymous_github/commit/8221b2ee7ff558a496ba29e8e41c33baee1021f5)

**Comment by mnagired** [comment]
Thank you for your quick reply!

However, I still see the issue where the notebook is fine on GitHub but then duplicated in the anonymous version. 

Do you recommend removing this anonymous repository and re-anonymizing the original GitHub repo? @tdurieux

Thanks for your help.

**Comment by tdurieux** [comment]
Forced refresh your page. It should work, i tested with one of your repo.

**Comment by mnagired** [comment]
Thanks a lot for your help! 

Oddly enough, it works properly on some browsers (Google Chrome, Firefox, Opera) but fails to work on Safari. I've tried clearing my cache on Safari multiple times but I'm not sure why this is occurring. Do you have any insight into this or should I just stick to other browsers? Thanks.

**Comment by tdurieux** [comment]
I fail in reproducing on safari (not mobile). I believe it only happens on your browser.
